version: '3'

services:
  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "./mysql:/var/lib/mysql"
    restart: always
    ports:
      - '3306:3306'
  app:
    build: .
    env_file: .env
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/youtubedl
    ports:
      - "8000:8000"
    depends_on:
      - db